add lean mail updates

diff --git a/src/main/resources/scripts/redeploy b/src/main/resources/scripts/redeploy
--- a/src/main/resources/scripts/redeploy
+++ b/src/main/resources/scripts/redeploy
@@ -8,16 +8,19 @@ set -e
 # Read configuration file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-TRAIN_RESULT=./train 	#train the models
+TIMESTAMP=`date +"%Y%m%d-%H%M%S"`
+
+TRAIN_SOURCE=source ./train
+TRAIN_RESULT=$? 	#train the models
 
 ######################
 # Start of training notification - enable if required
 ######################
-echo -n "Training ended with return value $TRAIN_RESULT at " | tee -a $LOG_FILE
-date | tee -a $LOG_FILE
+echo -n "Training ended with return value $TRAIN_RESULT at "
+date
 
 if [[ $TRAIN_RESULT -ne 0 ]]; then
-  #mail -s "Error in train: $EMAIL_SUBJECT $TIMESTAMP" -a "From: $FROM_EMAIL" $TARGET_EMAIL < $LOG_FILE
+  #echo "Training failed due to few errors at $TIMESTAMP. Visit logs for more details." | mail -s "Error in train: $EMAIL_SUBJECT $TIMESTAMP" -a "From: $FROM_EMAIL" $TARGET_EMAIL
   echo -n "Train script aborted at "
   date
   exit 1
@@ -27,16 +30,17 @@ fi
 # End of training notification
 ######################
 
-DEPLOY_RESULT=[ $TRAIN_RESULT -eq 0 ] && ./deploy	#deploy the trained models (if there was no errors)
+DEPLOY_SOURCE=source ./deploy
+DEPLOY_RESULT=$?	#deploy the trained models (if there were no errors)
 
 ######################
 # Start of deploy notification - enable if required
 ######################
-echo -n "Deploy ended with return value $DEPLOY_RESULT at " | tee -a $LOG_FILE
-date | tee -a $LOG_FILE
+echo -n "Deploy ended with return value $DEPLOY_RESULT at "
+date
 
 if [[ $DEPLOY_RESULT -ne 0 ]]; then
-  #mail -s "Error in train: $EMAIL_SUBJECT $TIMESTAMP" -a "From: $FROM_EMAIL" $TARGET_EMAIL < $LOG_FILE
+  #echo "Deployment failed due to few errors at $TIMESTAMP. Visit logs for more details." | mail -s "Error in deploy: $EMAIL_SUBJECT $TIMESTAMP" -a "From: $FROM_EMAIL" $TARGET_EMAIL
   echo -n "Deploy script aborted at "
   date
   exit 1
@@ -53,7 +57,7 @@ fi
 ######################
 
 if [ $TRAIN_RESULT -eq 0 ] && [ $DEPLOY_RESULT -eq 0 ]; then
-  #mail -s "Normal: $EMAIL_SUBJECT $TIMESTAMP" -a "From: $FROM_EMAIL" $TARGET_EMAIL < $LOG_FILE
+  #echo "Successfully redeployed pipeline at $TIMESTAMP. Visit logs for more details." | mail -s "Normal: $EMAIL_SUBJECT $TIMESTAMP" -a "From: $FROM_EMAIL" $TARGET_EMAIL
   echo -n "Successfully redeployed pipeline at "
   date
   exit 1
